version: '3.9'

services:
  app:
    container_name: medods_app
    image: headgardener1/medods_app:latest
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=mongodb://mongo_db:27017
      - DATABASE_USER=yan
      - DATABASE_PASSWORD=3418abcd
      - DATABASE_NAME=medods
      - COLLECTION=tokens
      - ACCESS_TOKEN_SECRET_KEY=secret
      - ACCESS_TOKEN_TTL=15
      - REFRESH_TOKEN_INITIAL_LEN=32
      - REFRESH_TOKEN_TTL=60
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    container_name: medods_mongo_db
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yan
      - MONGO_INITDB_ROOT_PASSWORD=3418abcd
